project:
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js

website:  
  repo-url: https://github.com/jonjunduan/r-shinylive-demo
  repo-actions: [edit, issue]
  title: "r-shinylive in Quarto"
  navbar:
    search: false
    left:
      - text: "BC Retial and Trade App (Home)"
        file: bc-retail-r-shinylive.qmd
      - text: "Skeletal Template"
        file: template-r-shinylive.qmd
      - text: "Tutorial"
        file: index.qmd



format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 200px
    toc: true

